### ISSUE TITLE
Feature request: date component orders

### ISSUE THREAD

**Issue by dagwud** [wassy92x/lovelace-digital-clock#1]
I feel bad opening what appears to be the first issue, so...

First up, thank you: this is pretty close to exactly the component I was looking for.

That said, please could you consider a way to reorder the date components?

As an example:
```
    dateFormat:
      weekday: long
      day: 2-digit
      month: long
```
renders out as:
Tuesday, June 22

I would like to rearrange it to be "Tuesday, 22 June" (call it a regional/localization issue... )

Thanks!
