### ISSUE TITLE
Custom element not found: digital-clock

### ISSUE THREAD

**Issue by NVader2000** [wassy92x/lovelace-digital-clock#13]
Just installed, created a custom card, and pasted the following. What am I missing?

type: 'custom:digital-clock'
dateFormat:
  weekday: 'long'
  day: '2-digit'
  month: 'short'
timeFormat:
  hour: '2-digit'
  minute: '2-digit'

**Comment by wassy92x** [comment]
Your indentation is wrong.
```
type: 'custom:digital-clock'
dateFormat:
  weekday: 'long'
  day: '2-digit'
  month: 'short'
timeFormat:
  hour: '2-digit'
  minute: '2-digit'
```
But this can't be the reason for custom elemente not found. Please restart your browser or if it is on your mobile phone, please clear the cache of your app and stop it. After this you can open the app again and the element should be available
