### ISSUE TITLE
Question: 24h clock available?

### ISSUE THREAD

**Issue by lijnkampioen** [wassy92x/lovelace-digital-clock#14]
Hi,

First of all, thanks for the work you did creating this HA addon.

Is there any way to show a 24h clock rather than AM/PM.

Many thanks in advance!
Koen

**Comment by wassy92x** [comment]
Yes this is possible.
Whether the 12 hour or 24 hour format is used is primarly dependent on the used locale.
So either specifiy a correct locale in your home assistant profile or override the automatically detected format by setting hour12 to false:
```
type: custom:digital-clock
timeFormat:
  hour: '2-digit'
  minute: '2-digit'
  hour12: false
```
