### ISSUE TITLE
Year in date line

### ISSUE THREAD

**Issue by dalwhin** [wassy92x/lovelace-digital-clock#3]
Thanks a lot for this wonderful digital clock. It's not an issue, what I am writing. Just an idea. Instead of only:

Donnerstag, 24. Juni

Will it be possible to have:

Donnerstag, 24. Juni 2021

With datefFormat year: short/long

Thanks a lot

**Comment by wassy92x** [comment]
This will be possible by setting dateFormat to
```
dateFormat:
  weekday: long
  day: 2-digit
  month: short
  year: numeric
```
