### ISSUE TITLE
can't add tap actions

### ISSUE THREAD

**Issue by akuehner** [wassy92x/lovelace-digital-clock#32]
This clock was perfect for my needs, wanted a very small clock for a small panel I have running. However I was trying to add a tap action, to navigate to another dashboard with more calendar info, but the tap options don't seem to actually work.
Any thoughts?

```
type: custom:digital-clock
tap_action:
  action: navigate
  navigation_path: /living-room/calendar
```
