### ISSUE TITLE
Possibility to change fontsize

### ISSUE THREAD

**Issue by rogerbille** [wassy92x/lovelace-digital-clock#4]
Thanks for your card. I would like to use this on my wallpanel however I would need a larger font. The time (firstline need to baout 3x larger). I would like to see an option to set the fontsize for both the first and second line. The card height either need to autoadjust so the text can be seen or it is also configurable. E.g.

```
type: 'custom:digital-clock'
dateFormat:
  weekday: 'long'
  day: '2-digit'
  month: 'short'
  fontsize: 12px
timeFormat:
  hour: '2-digit'
  minute: '2-digit'
  fontsize: 36px
```
