### ISSUE TITLE
24H format?

### ISSUE THREAD

**Issue by maxwolfen** [wassy92x/lovelace-digital-clock#43]
Sorry if i ask a noob question. But is it posible to change the time to 24H format rather than AM/PM? 

Thanks in advance :) 

//Max

**Comment by mennovanhout** [comment]
Heya, I had the same question.

I dove inside the source code here at Github and found the fix:

```
- type: 'custom:digital-clock'
  dateFormat:
    weekday: 'long'
    day: '2-digit'
    month: 'long'
  timeFormat: 'HH:mm'
```

Instead of:

```
type: 'custom:digital-clock'
dateFormat:
  weekday: 'long'
  day: '2-digit'
  month: 'short'
timeFormat:
  hour: '2-digit'
  minute: '2-digit'
```


I found out that the source code checks if the timeFormat is a string if so he will use that format, if it's an object he will always use 12 hour with the corresponding config. My top comment should fix it :D

**Comment by maxwolfen** [comment]
Ah, that worked great 👍  thanks alot! 😊

**Comment by Microweave98** [comment]
Might be another dumb question but is there a way to only do that for one user?

**Comment by mennovanhout** [comment]
> - type: 'custom:digital-clock'
>   dateFormat:
>     weekday: 'long'
>     day: '2-digit'
>     month: 'long'
>   timeFormat: 'HH:mm'

Just make 2 cards and use the visibility condition and yes than you have it!
![image](https://github.com/user-attachments/assets/d5d87e95-bb89-4c7f-b890-55f91816b010)

**Comment by wassy92x** [comment]
Another possibility is to set the timeFormat to
```
timeFormat:
  hour: 2-digit
  minute: 2-digit
  hour12: false
```
