### ISSUE TITLE
Clock/date only option

### ISSUE THREAD

**Issue by maceddy** [wassy92x/lovelace-digital-clock#45]
Is there a way to split the date and time?

I want this on separate area's on my dashboard.

**Comment by videojedi** [comment]
Try making two cards and doing this

```
type: 'custom:digital-clock'
dateFormat: ' '
timeFormat:
  hour: '2-digit'
  minute: '2-digit'
```

```
type: 'custom:digital-clock'
dateFormat:
  weekday: 'long'
  day: '2-digit'
  month: 'short'
timeFormat: ' '
```
