### ISSUE TITLE
show year ?

### ISSUE THREAD

**Issue by myB0B** [wassy92x/lovelace-digital-clock#48]
possible to add the possibility to show year ?

**Comment by wassy92x** [comment]
This is already possible by setting the secondLineFormat to
```
secondLineFormat:
  weekday: short
  day: 2-digit
  month: short
  year: short
```
Also you can set year to `long` to show 4 digits

**Comment by myB0B** [comment]
Sorry but this is not working

**Comment by wassy92x** [comment]
Please show me your yaml configuration

**Comment by myB0B** [comment]
type: custom:digital-clock
dateFormat:
  weekday: long
  day: 2-digit
  month: long
timeFormat:
  hour: 2-digit
  minute: 2-digit

adding year to dateFormat result of a blank screen

using ;
secondLineFormat:
  weekday: short
  day: 2-digit
  month: short
  year: short

has no effect

**Comment by wassy92x** [comment]
Sorry, it was the wrong value. Please set year to numeric or 2-digit.

```
type: custom:digital-clock
dateFormat:
  weekday: long
  day: 2-digit
  month: long
  year: numeric # or 2-digit
timeFormat:
  hour: 2-digit
  minute: 2-digit
```
