### ISSUE TITLE
Support Timezone

### ISSUE THREAD

**Issue by paulo-graca** [wassy92x/lovelace-digital-clock#7]
It seams the addon is using the browser Timezone. I'm not sure why, but for 2 different devices I have different timezones. I started noticing this recently. Perhaps related with countries summer time changes, not sure. Besides locale, could this addon also support timezone?

**Comment by wassy92x** [comment]
As you noticed, the timezone is currently set by the browser itself.
I could try to implement an additional option to set an optional timezone.
A PR would also be welcome.

**Comment by rbflurry** [comment]
Can confirm, This issue just started happening with a fire tablet.

```
type: custom:digital-clock
firstLineFormat:
  hour: 2-digit
  minute: 2-digit
secondLineFormat:
  weekday: long
  day: 2-digit
  month: long
```
